### ISSUE TITLE
Mcustiel\Phiremock\Client\Phiremock\createExpectation falls in timeout

### ISSUE THREAD

**Issue by maximelebastard** [mcustiel/phiremock#11]
Hi,

I use Phiremock with the extension for codeception. When I create the same expectation a few times (about 15), the test command freezes.

After some debugging, I found out that the request created in Mcustiel\Phiremock\Client\Phiremock\createExpectation sometimes falls in timeout. I tried to add a timeout option to the Guzzle client, but it stills freeze.

Do you know how I can get some more information about this for debugging ? It seems that it is caused by the phiremock CLI that does not respond after a few calls to its api. 

The bin/phiremock file uses Monolog, but where does Monolog writes its logs ?

**Comment by mcustiel** [comment]
Hi. When using the extension for codeception there is a log option in the extension configuration to choose to which directory the log is written. By default is codeception's _output directory. There's also the possibility to use debug option.
