### ISSUE TITLE
Mock endpoint with query string doesn't match

### ISSUE THREAD

**Issue by fenos** [mcustiel/phiremock#16]
Hi again, thanks a lot for this awesome library.

I came across a weird behavior, which I don't understand if it was by design or if it is a bug, please advise.

In my code I'm making a call to  
`GET /users?filters[id][0]=1&filters[id][1]=2&filters[id][3]=3`

in my test, I'm trying to create an endpoint to phiremock that match exactly that `url + querystring`

ex:

```php
$this->phiremock->expectARequestToRemoteServiceWithAResponse(
	Phiremock::on(
        A::getRequest()
		->andUrl(Is::equalTo('/users?filters[id][0]=1&filters[id][1]=2&filters[id][3]=3'))
	)->then(
		Respond::withStatusCode($this->status_code);
	)
);
```

The call fails, not matching the `Phiremock endpoint` if I instead don't assert the `query string` and use only `Is::equalTo('/users')` that works. 

My expectation was to see it pass if the url fully matches.

Any thoughts? 👍

**Comment by fenos** [comment]
Hi, I just find out what's the issue! 🎉 
I'm making an http call using `Guzzle` which it encodes the query string parameters, for this reason, the asserted URL doesn't match. However, if I encode the url on the assertion that works! 😄

**Comment by mcustiel** [comment]
Hey, @fenos 
Thank you for the info. I will add a test to cover this case.
