### ISSUE TITLE
Shorter syntax to create simple expectation (suggestion)

### ISSUE THREAD

**Issue by rlanvin** [mcustiel/phiremock#29]
First, I'd like to say thank you for this library!

The only annoyance I'm having at the moment is that it's a bit awkward to create a simple expectation, and the tests I write end up to be hard to read because of this.

So I'd like to suggest a shortcut for simple use cases, something like:

    $phiremock->on('GET','/my/url')->then(200, $content); 

1. `on()` is not static anymore (one can always call new ExpectationBuilder manually if necessary)
2. `on()` can either take a `RequestBuilder` (unchanged behavior) or 2 strings, in which case it builds `RequestBuilder::create($param1)->andUrl(Is::EqualTo($param2))` by default
3. `then()` can either take a `ResponseBuilder` (unchanged behavior) or 2 strings, in which case it builds `Respond::withStatusCode($param1)->andBody($param2)`

This way it would take 1 line to write expectation for common use cases instead of the 8-10 needed at the moment.

What do you think? Is it something you would consider accepting as a PR?

**Comment by mcustiel** [comment]
Hi! Thanks for your suggestion. I really like the idea. Anyhow I would maintain the static approach because of how phiremock is used in the codeception extension. I think it gives more flexibility to have a static request builder creator.
I would suggest to have a method that identifies the short definition like Phiremock::onRequest('GET', 'path')->then(200, $content) to keep the methods simple and not create forks based in the method arguments. Using this approach this new method could also be used in the codeception extension. 
What do you think?

**Comment by rlanvin** [comment]
> Anyhow I would maintain the static approach because of how phiremock is used in the codeception extension.

Alright. I have no idea what the codeception extension does, so I won't argue here.

> I would suggest to have a method that identifies the short definition like Phiremock::onRequest('GET', 'path')->then(200, $content) to keep the methods simple and not create forks based in the method arguments.

I'm not sure I understand what you mean. I'm not suggesting to have different *forks*, but simply to check the parameter type in the method. For example (simplified):

    function on($param1, $param2 = '') {
        if ( $param1 instanceof RequestBuilder) {
            // proceed as currently
        } else {
            // do a RequestBuilder::create($param1)->andUrl(Is::EqualTo($param2))
        }
    }

If `on` stays static as you suggest, then it won't even break backwards compatibility and be completely transparent. If you only need to match the request method and the URL, you can use the short syntax, otherwise you keep using it as it is now. I don't see why it would be necessary to have two different methods?

**Comment by mcustiel** [comment]
Added the short syntax in v1.7.1
