### ISSUE TITLE
Multiple matches per Is:matching() (Question)

### ISSUE THREAD

**Issue by buflix** [mcustiel/phiremock#33]
Is there a way to get all (global) matches with one (or multiple) matcher?

Example Request:
``
[
  {
    "name": "Foo"
  },
  {
    "name": "Bar"
  }
]
``

So I can use this matches (in this example "names") in response by '{body.1}' , '{body.2}' and so on...

In a nutshell: I need a preg_match_all ;-)

**Comment by buflix** [comment]
I created a PR to resolve this issue ;-)

**Comment by mcustiel** [comment]
Hi @buflix 
Sorry for the delay, I see you already answered yourself. Will check your PR. Thank you.

**Comment by mcustiel** [comment]
Added in v1.8.0. Many thanks to @buflix

**Comment by troublete** [comment]
Fantastic! Thank you so much.

**Comment by buflix** [comment]
Thank you too. This will help me a lot.
