### ISSUE TITLE
Symfony4 (in)compatibility

### ISSUE THREAD

**Issue by Wirone** [mcustiel/phiremock#35]
Phiremock v1.8.0 requires `symfony/cache` in `^3.1` so when I want to install it in SF4 project it rises error: "Your requirements could not be resolved to an installable set of packages".

**Comment by Wirone** [comment]
AFAIS there is compatible [fork](https://github.com/andriuspetrauskis/phiremock), available on Packagist under [`phiremock/phiremock`](https://packagist.org/packages/phiremock/phiremock). Which is weird, since somebody took your work and is using under vendor name which looks like official :(

**Comment by mcustiel** [comment]
Hello @Wirone. Thanks for reporting this, I will fix it as soon as I have some free time. My family got bigger recently and it is being difficult to dedicate time to my github projects.

**Comment by Wirone** [comment]
@mcustiel congrats! :) Family first, I understand it totally.

**Comment by mcustiel** [comment]
Added in version 1.9
