### ISSUE TITLE
Comparing request data structures

### ISSUE THREAD

**Issue by Wirone** [mcustiel/phiremock#36]
We need to make expectations for explicit JSON structures, but:

- we want whitespaces to be ignored
- don't want to write complex regexes

In other words, we would like to match that, for example, this was sent through request:
`{"name": "John", "surname": "Deer", "tags": ["a", "b"]}`

even if it was sent in pretty format:

```
{
    "name": "John",
    "surname": "Deer",
    "tags": ["a", "b"]
}
```
or condensed:
`{"name":"John","surname":"Deer","tags":"a","b"]}`
or even in different order:
`{"name": "John", "tags": ["a", "b"], "surname": "Deer"}`

Recursivity should be supported.

**Comment by mcustiel** [comment]
This is a nice suggestion, thank you. I started to work on it in a feature branch.

**Comment by mcustiel** [comment]
Hey @Wirone 
Could you please check the pull request #37 and see if that solves the issue?
Thanks

**Comment by mcustiel** [comment]
Added in version 1.9

**Comment by Wirone** [comment]
Sorry, I couldn't check it in past days due to deadlines :( I'll give it a shot in upcoming days.
