### ISSUE TITLE
Matching by sameJsonObjectAs does not work correctly

### ISSUE THREAD

**Issue by Delorien84** [mcustiel/phiremock#38]
Hi, 
 I have tested new feature `Is::sameJsonObjectAs`. I have found that matching does not work correctly when similar request are made.

Lets have two POST requests with following jsons:
`{ "foo": "1"}` and `{ "foo": "1", "bar": "2"}`.

When writing expectation like: `A::postRequest()->andUrl(Is::equalTo("/api"))->andBody(Is::sameJsonObjectAs('{ "foo": "1", "bar": "2"}'));`

The expectation always return me two matches. It should return one match.

**Comment by mcustiel** [comment]
Thanks for reporting it, @Delorien84 . Will fix it as soon as possible.

**Comment by mcustiel** [comment]
Fixed in v1.9.1.

**Comment by Delorien84** [comment]
Working, thanks
