### ISSUE TITLE
Support of reactphp/http in newest version(v0.8.3)

### ISSUE THREAD

**Issue by kordos** [mcustiel/phiremock#43]
I'm using newest version of reactphp/http(v0.8.3) but your project is locked on 0.7.x version and because of that I can't use it. I'm using features from 0.8 version so I can't downgrade that library.

Could you update your project to 0.8.x version?

Regards,
Kordos

**Comment by kordos** [comment]
Any progress with that?

**Comment by mcustiel** [comment]
Hi @kordos. The change is already on dev-master. I need to test it properly. There will be a new version in the next days.

**Comment by kordos** [comment]
Great, thanks :)

**Comment by mcustiel** [comment]
Fixed in v1.11.0
