### ISSUE TITLE
[Request] Split packages

### ISSUE THREAD

**Issue by Gounlaf** [mcustiel/phiremock#47]
Hi,

Could you consider to provide phiremock in different packages... at least `phiremock-client` and `phiremock-server`?

It would reduce dependencies when using the "client" part on a project.

Thanks,

Regards.

**Comment by Gounlaf** [comment]
I just saw theses packages already exists... sorry about that :confused:

**Comment by mcustiel** [comment]
No problem, this is something I also want, thanks for proposing it.
My idea is also to split the codeception extension and module.
My main issue right now is that I don't have enough time to work on my open source projects. I already have the split almost done, it will be phiremock v2, but I need to test it properly
